{{ if not .Values.application.enabled }}
{{- if .Values.logging }}
{{- if .Values.logging.enabled }}
{{- range .Values.logging.flows }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  labels:
{{ include "application.labels" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.logging.additionalLabels }}
{{ toYaml $.Values.logging.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.logging.annotations }}
  annotations:
{{ toYaml $.Values.logging.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}-{{ .name }}
spec:
  globalOutputRefs:
{{ toYaml .globalOutputRefs | indent 4 }}
  match:
    - select:
        labels:
{{ include "application.labels.selector" $ | indent 10 }}
  filters:
{{ toYaml .filters | indent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}