{{ if not .Values.application.enabled }}
{{- if .Values.serviceMonitor }}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
{{ include "application.labels" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
{{- end }}
{{- if or .Values.serviceMonitor.annotations }}
  annotations:
{{ toYaml .Values.serviceMonitor.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "application.name" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
{{ toYaml .Values.serviceMonitor.endpoints | indent 4 }}
{{- end }}
{{- end }}
{{- end }}